# Generated by Django 5.2.13 on 2026-04-20 21:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due', models.DateTimeField(default=django.utils.timezone.now)),
                ('stability', models.FloatField(default=0.0)),
                ('difficulty', models.FloatField(default=0.0)),
                ('state', models.CharField(choices=[('Learning', 'Learning'), ('Review', 'Review'), ('Relearning', 'Relearning')], default='Learning', max_length=32)),
                ('last_review', models.DateTimeField(blank=True, null=True)),
                ('fsrs_state', models.JSONField(blank=True, default=dict)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='study.deck')),
            ],
            options={
                'ordering': ['due', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Again'), (2, 'Hard'), (3, 'Good'), (4, 'Easy')])),
                ('due_before', models.DateTimeField()),
                ('due_after', models.DateTimeField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='study.card')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='deck',
            constraint=models.UniqueConstraint(fields=('owner', 'title'), name='unique_deck_title_per_user'),
        ),
    ]
