# Generated by Django 5.2.13 on 2026-04-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_userreviewschedule_reviewslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='has_article',
            field=models.BooleanField(default=False),
        ),
    ]
