# Generated by Django 5.2.13 on 2026-04-22 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_card_has_article'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_mode', models.CharField(choices=[('fsrs', 'FSRS'), ('typing_practice', 'Typing Practice'), ('article_practice', 'Article Practice')], max_length=32)),
                ('sentence', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_attempts', to='study.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
