# Generated by Django 5.2.13 on 2026-04-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_unique_user_email_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='context',
            field=models.CharField(blank=True, default='', help_text='Optional context for ambiguous cards.', max_length=255),
        ),
    ]
