# Generated by Django 5.2.13 on 2026-05-04 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_card_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=32)),
                ('task_type', models.CharField(blank=True, default='', max_length=32)),
                ('generated_prompt', models.TextField(blank=True, default='')),
                ('user_answer', models.TextField(blank=True, default='')),
                ('chatgpt_response', models.TextField(blank=True, default='')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Again'), (2, 'Hard'), (3, 'Good'), (4, 'Easy')], null=True)),
                ('active_use', models.BooleanField(default=False)),
                ('is_success', models.BooleanField(default=False)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('manual_rating', 'Manual rating'), ('pasted_chatgpt_response', 'Pasted ChatGPT response')], default='manual_rating', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_attempts', to='study.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_use_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardActiveState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('passive', 'Passive'), ('candidate', 'Candidate'), ('recall', 'Recall'), ('phrase', 'Phrase'), ('cloze', 'Cloze'), ('sentence', 'Sentence'), ('situation', 'Situation'), ('argumentation', 'Argumentation'), ('active', 'Active'), ('paused', 'Paused')], default='passive', max_length=32)),
                ('active_due', models.DateTimeField(blank=True, null=True)),
                ('active_fsrs_state', models.JSONField(blank=True, default=dict)),
                ('active_stability', models.FloatField(default=0.0)),
                ('active_difficulty', models.FloatField(default=0.0)),
                ('last_active_review', models.DateTimeField(blank=True, null=True)),
                ('active_started_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('total_active_attempts', models.PositiveIntegerField(default=0)),
                ('successful_active_attempts', models.PositiveIntegerField(default=0)),
                ('failed_active_attempts', models.PositiveIntegerField(default=0)),
                ('consecutive_active_failures', models.PositiveIntegerField(default=0)),
                ('recall_success_count', models.PositiveIntegerField(default=0)),
                ('phrase_success_count', models.PositiveIntegerField(default=0)),
                ('cloze_success_count', models.PositiveIntegerField(default=0)),
                ('sentence_success_count', models.PositiveIntegerField(default=0)),
                ('situation_success_count', models.PositiveIntegerField(default=0)),
                ('argumentation_success_count', models.PositiveIntegerField(default=0)),
                ('last_error_summary', models.TextField(blank=True, default='')),
                ('is_active_pipeline', models.BooleanField(default=False)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_state', to='study.card')),
            ],
            options={
                'ordering': ['active_due', 'card__created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivePracticeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_active_practice', models.BooleanField(default=True)),
                ('enable_active_fsrs', models.BooleanField(default=True)),
                ('current_level', models.CharField(default='A2-B1', max_length=32)),
                ('target_level', models.CharField(default='C1', max_length=32)),
                ('active_tasks_per_day', models.PositiveSmallIntegerField(default=5)),
                ('new_active_words_per_day', models.PositiveSmallIntegerField(default=1)),
                ('max_active_pipeline', models.PositiveSmallIntegerField(default=30)),
                ('active_overdue_pause_threshold', models.PositiveSmallIntegerField(default=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_practice_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
